<?php

/**
 * @file
 * Primary module hooks for Tenant module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tenant_form_system_site_information_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // append hint for provided front page
  $form['front_page']['site_frontpage']['#description'] .= ' ';
  $form['front_page']['site_frontpage']['#description'] .= t('Specify "/tenant/front" to dispatch front page by group membership status');
}
